# Generated by Django 4.2 on 2026-03-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="numéro")),
                ("street", models.CharField(max_length=64, verbose_name="rue")),
                ("city", models.CharField(max_length=64, verbose_name="ville")),
                ("state", models.CharField(max_length=2, verbose_name="état")),
                ("zip_code", models.PositiveIntegerField(verbose_name="code postal")),
                (
                    "country_iso_code",
                    models.CharField(max_length=3, verbose_name="code pays ISO"),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Letting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="titre")),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lettings.address",
                        verbose_name="adresse",
                    ),
                ),
            ],
        ),
    ]
